# Yaran World Generator by Kyle Nanakdewa
# Configuration

# Thank you for using Yaran! See my other plugins at http://plugins.akenland.com/

# Don't change the formatting of this file, or Bukkit will complain. To reset this config to default, just delete it.
# We recommend using VS Code (https://code.visualstudio.com/) to modify this file, as it will help you with formatting.
# Do NOT use tabs (tab indent) - use spaces. VS Code will automatically insert spaces, but other text editors won't.

# Full documentation can be found at http://akenland.com/plugins/yaran
# After editing this file, use "/yaran reload" to load your changes into the server.


generator-settings:

  simplex-octave:
    # Amount of octaves to create. Default 8.
    octaves: 8
    # Sets the scale used for all coordinates passed to this generator. This is the equivalent to setting each coordinate to the specified value. Default 0.005.
    scale: 0.005

    # How much to alter the frequency by each octave. Default 0.5.
    frequency: 0.5
    # How much to alter the amplitude by each octave. Default 0.5.
    amplitude: 0.5
    # If true, normalize the value to [-1, 1]. Default true.
    normalize: true

    # The maximum world height above the origin height. Default 15.
    maximum-height: 15
    # The origin height - the lowest point of the world. Default 50.
    origin-height: 50
    # The exponent to raise heights to. Default 1.
    exponent: 1

    # Whether to enable the 3D simplex octave generator.
    enable-3d: true
    # The threshold for 3D cutouts. Default 0.25.
    cutout-threshold: 0.25

  simplex-noise:
    # The frequencies to use. At least one is required. More will increase terrain variation.
    frequencies:
      - 1
      - 2
      - 4
    # The size of each frequency. Must be the same number of values as the list of frequencies.
    sizes:
      - 1
      - 0.5
      - 0.25
    # The exponent to raise noise to.
    exponent: 3

    # How far the terrain can be above the minimum height * total sizes * 4.
    amplitude: 1
    # The minimum terrain height. All terrain will be generated at or above this level.
    minimum-height: 50

    # Whether to perform 3D cutouts, creating overhangs and large caves.
    cutouts: true
    # Threshold for cutting out terrain to create overhangs. Higher numbers = less cutouts.
    cutout-threshold: 2
    # The frequencies to use. At least one is required. More will increase terrain variation.
    cutout-frequencies:
      - 1
      - 2
      - 4
    # The size of each frequency. Must be the same number of values as the list of frequencies.
    cutout-sizes:
      - 1
      - 0.5
      - 0.25

biome-color-mappings:
  0x00000070: ocean
  0x008DB360: plains
  0x00FA9418: desert
  0x00606060: mountains
  0x00056621: forest
  0x000B6659: taiga
  0x0007F9B2: swamp
  0x000000FF: river
  0x00FF0000: nether
  0x008080FF: the_end
  0x007070D6: frozen_ocean
  0x00A0A0FF: frozen_river
  0x00FFFFFF: snowy_tundra
  0x00A0A0A0: snowy_mountains
  0x00FF00FF: mushroom_fields
  0x00A000FF: mushroom_field_shore
  0x00FADE55: beach
  0x00D25F12: desert_hills
  0x0022551C: wooded_hills
  0x00163933: taiga_hills
  0x0072789A: mountain_edge
  0x00537B09: jungle
  0x002C4205: jungle_hills
  0x00628B17: jungle_edge
  0x00000030: deep_ocean
  0x00A2A284: stone_shore
  0x00FAF0C0: snowy_beach
  0x00307444: birch_forest
  0x001F5F32: birch_forest_hills
  0x0040511A: dark_forest
  0x0031554A: snowy_taiga
  0x00243F36: snowy_taiga_hills
  0x00596651: giant_spruce_taiga
  0x00454F3E: giant_spruce_taiga_hills
  0x00507050: wooded_mountains
  0x00BDB25F: savanna
  0x00A79D64: savanna_plateau
  0x00D94515: badlands
  0x00B09765: wooded_badlands_plateau
  0x00CA8C65: badlands_plateau
  0x000000AC: warm_ocean
  0x00000090: lukewarm_ocean
  0x00202070: cold_ocean
  0x00000050: deep_warm_ocean
  0x00000040: deep_lukewarm_ocean
  0x00202038: deep_cold_ocean
  0x00404090: deep_frozen_ocean
  0x00B5DB88: sunflower_plains
  0x00FFBC40: desert_lakes
  0x00888888: gravelly_mountains
  0x002D8E49: flower_forest