# Yaran World Generator by Kyle Nanakdewa
# Configuration

# Thank you for using Yaran! See my other plugins at http://plugins.akenland.com/

# Don't change the formatting of this file, or Bukkit will complain. To reset this config to default, just delete it.
# We recommend using VS Code (https://code.visualstudio.com/) to modify this file, as it will help you with formatting.
# Do NOT use tabs (tab indent) - use spaces. VS Code will automatically insert spaces, but other text editors won't.

# Full documentation can be found at http://akenland.com/plugins/yaran
# After editing this file, use "/yaran reload" to load your changes into the server.


# The websocket URL (endpoint) for the Atlas server. Default "ws://localhost:8080".
ws-url: ws://localhost:8080

generator-settings:
  simplex-octave:
    # Amount of octaves to create. Default 8.
    octaves: 8
    # Sets the scale used for all coordinates passed to this generator. This is the equivalent to setting each coordinate to the specified value. Default 0.005.
    scale: 0.005

    # How much to alter the frequency by each octave. Default 0.5.
    frequency: 0.5
    # How much to alter the amplitude by each octave. Default 0.5.
    amplitude: 0.5
    # If true, normalize the value to [-1, 1]. Default true.
    normalize: true

    # The maximum world height above the origin height. Default 15.
    maximum-height: 15
    # The origin height - the lowest point of the world. Default 50.
    origin-height: 50
    # The exponent to raise heights to. Default 1.
    exponent: 1