name: Yaran
version: 1.2
description: The Akenland world generator.
author: Kyle Nanakdewa
website: https://plugins.akenland.com/

api-version: 1.14
main: com.kylenanakdewa.yaran.YaranPlugin
load: startup

commands:
  yaran:
    description: View plugin information, and reload the plugin.
    permission: yaran.admin
    usage: /yaran <version/reload>
  2dnoise:
    description: Generate 2D Simplex Noise terrain in the selected WorldEdit region.
    permission: yaran.admin
    usage: /2dnoise <block pattern> <amplitude> [frequency:size],[frequency:size]... [exponent]